### ISSUE TITLE
[FEATURE] Support Windows and Linux builds

### ISSUE THREAD

**Issue by eddiehoyle** [eddiehoyle/screenspace#3]
## Summary
Test Windows and Linux builds. Contributors welcome!

## Operating systems
- [x] Osx 10.14
- [x] Arch Linux
- [x] Windows

## Maya versions
- [x] 2018

## Additional context
Update docs where needed also.

**Comment by Muream** [comment]
I built it just fine on Arch Linux

**Comment by charliewales** [comment]
Hi. Is it possible to compile for Maya 2017 on windows?

**Comment by eddiehoyle** [comment]
Hey @charliewales, I imagine this plugin _should_ be supported by all Maya versions with Viewport 2.0 (2016 onwards) and I only have OSX (10.14) at home so can't test Windows builds, sorry!

**Comment by charliewales** [comment]
Hi. The thing is I got it compiling for 2018 and 2019 changing a couple of errors (cannot recall now what I did :grinning:) but trying to compile for Maya 2017 is giving me almost 100 errors in Visual Studio. Sorry but I am not that used to compiling and I really do jot know how to debug C++, or C++ in general. I will post some images when I can. After the weekend.

**Comment by eddiehoyle** [comment]
Could you paste the build log here? The errors are likely just API changes between versions.

**Comment by eddiehoyle** [comment]
@charliewales, I think I've got this figured out. Could you give the `supportMaya2017` branch a try? Try these steps from your screenspace directory.

```bash
$ git pull
$ git checkout supportMaya2017
```

Then just follow the same build steps in the [README.md](https://github.com/eddiehoyle/screenspace/blob/develop/README.md#building)

Here's the PR: https://github.com/eddiehoyle/screenspace/pull/9

**Comment by charliewales** [comment]
Hi. It did the trick. I had to change a couple of thing but it compiled.

1. edited CMakeLists.txt
    set(MAYA_VERSION 2017)

In Visual Studio 2017:

2. I had to create a new solution for x64
3.  I had to remove 
   /machine:X86 
  in the linker command line section
3. In log.cc i commented line 16:
    *( m_log.m_stream ) << "[" << prefix << "]: ";
  i threw this error: 
     Error	C2679	binary '<<': no operator found which takes a right-hand operand of type 'const std::string' (or there is no acceptable conversion) .\src\ss\Log.cc	16	

4. In PickableDrawOverride.cc I changed:
Error	C2440	'static_cast': cannot convert from 'float' to 'screenspace::VerticalAlign'	screenspace	line 180
float _verticalAlign;
to
short _verticalAlign;

5. Also in PickableDrawOverride.cc line 306
Error	C2065	'M_PI': undeclared identifier
i just changed M_PI to 3.14159 i guess it may be acceptable

Thanks.

**Comment by eddiehoyle** [comment]
That's great! And thanks heaps for the numbered list, that's a huge help. I'll prep a PR with some Windows friendly changes to these files.

**Comment by eddiehoyle** [comment]
Hey @charliewales, would you mind giving this branch a test? You'll still need to apply the first 1-3 steps from above.

PR: https://github.com/eddiehoyle/screenspace/pull/10
Branch: `fixWindowsBuild`

```sh
$ git checkout develop
$ git pull
$ get checkout fixWindowsBuild
$ # Build, etc...
```

**Comment by charliewales** [comment]
On holidays. Not near a computer till Monday :grinning: I will give it a go then. Thanks

**Comment by charliewales** [comment]
So I did manage to compile but iI had to change this line again, also some warnings:
![imagen](https://user-images.githubusercontent.com/2865181/62413578-bb52ab80-b610-11e9-8a05-9c53abfafd85.png)

float increment = 2.0 * M_PI / float(num);
to
float increment = 2.0 * 3.14159 / float(num);


Thanks for the effort. Cheers.

**Comment by takavfx** [comment]
I did it with `fixWindowsBuild` branch and @charliewales's fix tip and worked.

**Comment by eddiehoyle** [comment]
Hey @takavfx, appreciate the feedback! I was hopeful the `M_PI` changes would work on Windows, looks like I'm missing something. I'll give this another go.

**Comment by pablosza** [comment]
this work in maya 2019?

**Comment by pablosza** [comment]
I have errors to install in maya 2017 too, when I try to run the git shell  say:  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

**Comment by eddiehoyle** [comment]
> this work in maya 2019?

Yes, it does.

> I have errors to install in maya 2017 too, when I try to run the git shell say: is not a full path and was not found in the PATH.

I'll chat to you offline about this, @pablosepulvedaz. We'll need to look into your build setup.

In the mean time, I made one last change that should fix the `M_PI` issue. Gonna merge the PR: #10!

**Comment by eddiehoyle** [comment]
Closing. Fixes for Maya 2017 and Windows builds will be available in `0.1.1`

**Comment by charliewales** [comment]
Hey. I gave a go to version 0.1.1 and the M_PI issue still persists. 
Tested on Windows 10 x64, Maya 2017, 2018 and 2019.
Thanks.

Note: where should I post possible feature requests?

**Comment by eddiehoyle** [comment]
Sigh, I really need need a PC.

I've just deprecated `0.1.1`, hard-coded `M_PI` and re-released as `0.1.2`. This should work now, thanks for testing!

As for feature requests, you should just be able to [make a new issue](https://help.github.com/en/articles/creating-an-issue) and we'll take it from there.

**Comment by wojtekjakubo** [comment]
Hi! Newbie here. Sorry for the question, but I cannot build it still for windows:

OpenMaya.lib(OpenMaya.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86' [E:\Personal\Software\MAYATOOLS\screenspace-develop\build\src\screenspace.vcxproj]

I've tried to change target build via VSC17 and even build it from there, but failing every time on this one.

Tried to launch cmake from vcvarsall.bat too.

Btw. "make" command is not working, I have to build it by 'cmake --build .' command.

Any help appreciated. Sorry for the basic question.

Cheers,
Wojtek

**Comment by eddiehoyle** [comment]
Hi Wojtek,

I don't have a Windows box unfortunately, these types of questions are
always tricky for me. I'll give them a go, though!

*> OpenMaya.lib(OpenMaya.dll) : fatal error LNK1112: module machine type
'x64' conflicts with target machine type 'x86' *
This sounds like something Charlie encountered when he was testing Windows
builds for me. He mentions creating "a new solution" and something to do
with removing linker:x86 section:
https://github.com/eddiehoyle/screenspace/issues/3#issuecomment-513918836

*> Btw. "make" command is not working, I have to build it by 'cmake --build
.' command.*
This is fine, although I'm a little surprised make doesn't work for you
here. What errors are you seeing?

Hope this helps!

Eddie

**Comment by eddiehoyle** [comment]
Hi @wojtekjakubo ,

I don't have a Windows box unfortunately, these types of questions are always tricky for me.

> OpenMaya.lib(OpenMaya.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86' ...

This sounds like something @charliewales encountered when he was testing Windows
builds (https://github.com/eddiehoyle/screenspace/issues/3#issuecomment-513918836). Maybe he could help?

> Btw. "make" command is not working, I have to build it by 'cmake --build.' command.

I'm a little surprised make doesn't work for you. What errors are you seeing?

**Comment by wojtekjakubo** [comment]
Thanks!

I managed to finally build it. Silly me - i had to configure CMAKE to build for Win64, it defaults to Win32 otherwise.

As for "make" - well, simply Windows doesn't have automake :) You have to build source via Visual Studio or "cmake --build ."

Everything works now, many thanks for this awesome plugin :)

Cheers!
Wojtek

**Comment by eddiehoyle** [comment]
Hell yeah, that's great news. Would you mind documenting how you managed these steps?

> i had to configure CMAKE to build for Win64, it defaults to Win32 otherwise.

and

> You have to build source via Visual Studio or "cmake --build ."

I'll get them added to documentation for future Windows friends.

**Comment by wojtekjakubo** [comment]
Ok, I have Visual Studio Community installed with Unity so currently it's version 2017 and the procedure goes like this:

in /build:
cmake -G "Visual Studio 15 2017 Win64" ..

then to build the .mll plugin:
cmake --build .

where '-G "Visual Studio 15 2017" is generator of the project for the VS compiler (in this case version VS 15 2017) and "Win64" is platform, and since Maya is 64bit only it's necessary to specify x64 architecture, because 'cmake' sets Win32 by default for Visual Studio.

Hope it helps anyone :)

Cheers,
Wojtek
